name: Scrape 1HD

on:
  schedule:
    - cron: '0 0 * * 0'  # This will run every Sunday at midnight
  workflow_dispatch:  # Allows manual trigger of the workflow

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install beautifulsoup4 requests

    - name: Run the script
      run: python 1hd.py  # Change to the correct name of your script file

    - name: Commit and push changes
      run: |
        git config --local user.email "your-email@example.com"
        git config --local user.name "GitHub Actions"
        git add new.m3u8
        git commit -m "Update new.m3u8 with latest m3u8 links" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
